# <LICENSE
# LICENSE>

env = Environment(CC = 'gcc',
                  CCFLAGS = '-Wall -O3 -ffast-math',
                  CPPPATH = '.')

SConscript('SConscript', exports = 'env')

env.Program('test_csparse.c', LIBS = 'csparse', LIBPATH = '.')
