// <LICENSE
//   ttauto: a C++ library for building train track automata
//
//   https://github.com/jeanluct/ttauto
//
//   Copyright (C) 2010-2026  Jean-Luc Thiffeault   <jeanluc@math.wisc.edu>
//                            Erwan Lanneau <erwan.lanneau@ujf-grenoble.fr>
//
//   This file is part of ttauto.
//
//   ttauto is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   ttauto is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with ttauto.  If not, see <http://www.gnu.org/licenses/>.
// LICENSE>

// Census for issue #23: how large are the sets the completion bound
// minimises over, in ttauto's own automata?
//
// For every stratum with n punctures: the dimension d, the vertices, the
// order of the group generated by the folds' permutation parts, and, from
// start vertex 0, the sizes of R(v) (permutation products of paths back to
// the start, from which the total permutations H come) and U(v) (their
// unit positions, from which P comes), over the vertices that can return.
// The bound as implemented tries 2^|P| |H| pairs per prefix.
//
// Build from the repository root, with the CMake build done (one line):
//   g++ -std=c++17 -O2 -Iinclude -Iextern/jlt
//     -Iextern/jlt/extern/CSparse/Include devel/iss023/census.cpp
//     lib/libttauto.a build/libcsparse.a -lm -o /tmp/census
// then run, for n from 4 to 6:
//   /tmp/census 4 6
// R(v) is skipped (shown as -) when group order times vertices exceeds a
// few million, where the sets would not fit comfortably in memory.

#include <algorithm>
#include <chrono>
#include <cstdlib>
#include <iostream>
#include <vector>
#include "traintracks/build.hpp"
#include "traintracks/traintrack.hpp"
#include "ttauto/completion_bound.hpp"
#include "ttauto/ttfoldgraph.hpp"

using traintracks::traintrack;

int main(int argc, char** argv)
{
  const int nlo = argc > 1 ? std::atoi(argv[1]) : 4;
  const int nhi = argc > 2 ? std::atoi(argv[2]) : 6;
  std::cout << " n stratum  d  vertices  group  |R| min..max  |U| min..max"
               "   d(d-1)  seconds\n";
  for (int n = nlo; n <= nhi; ++n)
    {
      jlt::vector<traintrack> ttv = traintracks::build_traintrack_list(n);
      for (int s = 0; s < (int)ttv.size(); ++s)
        {
          const auto t0 = std::chrono::steady_clock::now();
          const ttauto::ttfoldgraph<traintrack> g(ttv[s]);
          const long long G = ttauto::fold_group_order(g);
          std::cout << (n < 10 ? " " : "") << n << "  " << s+1 << "\t   "
                    << g.edges() << "  " << g.vertices() << "\t" << G << "\t";
          if (G * g.vertices() > 4000000)
            { std::cout << "  -\n"; continue; }
          const ttauto::completion_sets<traintrack> cs(g,0);
          std::size_t rlo = 0, rhi = 0, ulo = 0, uhi = 0;
          bool first = true;
          for (int v = 0; v < g.vertices(); ++v)
            {
              const std::size_t r = cs.completion_perms(v).size();
              const std::size_t u = cs.unit_positions(v).size();
              if (r == 0) continue;
              if (first) { rlo = rhi = r; ulo = uhi = u; first = false; }
              rlo = std::min(rlo,r); rhi = std::max(rhi,r);
              ulo = std::min(ulo,u); uhi = std::max(uhi,u);
            }
          const double dt = std::chrono::duration<double>(
            std::chrono::steady_clock::now() - t0).count();
          std::cout << rlo << ".." << rhi << "\t" << ulo << ".." << uhi << "\t"
                    << g.edges()*(g.edges()-1) << "\t" << dt << "\n";
        }
    }
}
