#!/usr/bin/env python3
"""Run bounds_toy over the configurations reported in pruning_bounds.tex
and write the tables to tables.tex.

Usage: python3 make_tables.py [path-to-bounds_toy-binary]

Build the binary first:  g++ -std=c++17 -O2 -o bounds_toy bounds_toy.cpp
Every row is checked against the reference list, the words found using the
Ham-Song norm test alone, which is guaranteed complete: a test passes when
it accepts exactly those words (compared by hash).  A test that misses
words is marked with how many, not dropped.
"""

import subprocess
import sys
import time

BIN = sys.argv[1] if len(sys.argv) > 1 else "./bounds_toy"

CONFIGS = [
    ("RL", "$\\{R,L\\}$, $d=2$", [3, 5, 8, 12, 20], ["HS", "C0", "C1", "C2"]),
    ("rauzy3", "all $I+e_{ab}$, $d=3$", [2.2, 2.5], ["HS", "C0", "C1", "C2"]),
    ("perm3", "shears and a 3-cycle, $d=3$", [2.0, 2.5, 3.0],
     ["HS", "C0", "C2", "BAD"]),
    ("sym3", "shears, a 3-cycle and a transposition, $d=3$: the folds' "
     "permutations generate all of $S_3$, as in \\ttauto's automata",
     [2.0, 2.5, 3.0], ["HS", "C0", "C2"]),
]

NAMES = {"HS": "norm only", "C0": "$C_0$ (current)", "C1": "$C_1$",
         "C2": "$C_2$ (new)", "BAD": "faulty, on purpose"}


def run(s, lam, c):
    t0 = time.time()
    out = subprocess.run([BIN, s, str(lam), c], capture_output=True, text=True,
                         check=True).stdout
    dt = time.time() - t0
    f = dict(kv.split("=") for kv in out.split()[1:] if "=" in kv)
    f["time"] = dt
    return f


def fmt_int(x):
    return "{:,}".format(int(x)).replace(",", "\\,")


def fmt_factor(x):
    if x >= 100:
        return fmt_int(round(x)) + "$\\times$"
    return "%.1f$\\times$" % x


def main():
    # Highlighting, for the results worth looking at (macros defined in
    # pruning_bounds.tex):
    #   \good   C_2 visits at most a tenth of what C_0 visits; C_2 wastes
    #           no prefix; C_2's longest prefix is the longest accepted word
    #           while C_0 goes further.
    #   \caught the deliberately faulty test missing words: the check working.
    lines = ["% Generated by make_tables.py; do not edit by hand."]
    for s, title, lams, crits in CONFIGS:
        lines += ["\\begin{table}[ht]", "\\centering", "\\small",
                  "\\begin{tabular}{rlrrrrrrrl}", "\\toprule",
                  "& & & & & & fewer & longest & longest & \\\\",
                  "$\\Lambda$ & test & accepted & classes & visited & wasted & "
                  "than $C_0$ & prefix & word & check \\\\", "\\midrule"]
        for lam in lams:
            res = {c: run(s, lam, c) for c in crits}
            truth = res["HS"]
            c0 = int(res["C0"]["visited"])
            word = int(truth["longest_accepted"])
            for c in crits:
                r = res[c]
                visited, wasted = int(r["visited"]), int(r["wasted"])
                longest = int(r["longest_prefix"])
                factor = c0 / visited
                missed = int(truth["accepted"]) - int(r["accepted"])
                cell_visited = fmt_int(visited)
                cell_factor = "" if c in ("HS", "C0") else fmt_factor(factor)
                cell_wasted = fmt_int(wasted)
                cell_longest = str(longest)
                if c == "C2":
                    if factor >= 10:
                        cell_visited = "\\good{%s}" % cell_visited
                        cell_factor = "\\good{%s}" % cell_factor
                    if wasted == 0 and visited > 1:
                        cell_wasted = "\\good{%s}" % cell_wasted
                    if word > 0 and longest == word and \
                            int(res["C0"]["longest_prefix"]) > word:
                        cell_longest = "\\good{%s}" % cell_longest
                if r["hash"] == truth["hash"]:
                    check = "reference" if c == "HS" else "finds all"
                else:
                    check = "misses %d" % missed
                    if c == "BAD":
                        check = "\\caught{%s}" % check
                lines.append(" & ".join([
                    str(lam) if c == crits[0] else "", NAMES[c],
                    fmt_int(r["accepted"]), fmt_int(r["classes"]),
                    cell_visited, cell_wasted, cell_factor, cell_longest,
                    str(word) if c == crits[0] else "", check]) + " \\\\")
                print(s, lam, c, visited, wasted, check, "%.1fs" % r["time"],
                      flush=True)
            lines.append("\\midrule" if lam != lams[-1] else "\\bottomrule")
        lines += ["\\end{tabular}",
                  "\\caption{%s.  Each row is a separate search; the columns "
                  "are explained in Section~\\ref{sec:check}.  Shaded green: "
                  "where the new test $C_2$ stands out.}" % title,
                  "\\label{tab:%s}" % s, "\\end{table}", ""]
    with open("tables.tex", "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
